apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  type: NodePort
  selector:
    app: orderservice
  ports:
    - protocol: TCP
      nodePort: 30083
      port: 9001
      targetPort: 9001